require("dotenv").config();
const mongoose = require("mongoose");
const Artwork = require("./models/artwork");

const artworks = [
  {
    title: "Abstract 1",
    slug: "abstract-1",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Abstract1.png",
  },
  {
    title: "Hitchcock",
    slug: "hitchcock",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Hitchcock.png",
  },
  {
    title: "Orchestrate",
    slug: "orchestrate",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Orchestrate.png",
  },
  {
    title: "Admiralbrücke",
    slug: "admiralbrucke",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/ADMIRALBRUCKE.png",
  },
  {
    title: "Ikejime",
    slug: "ikejime",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Ikejime.png",
  },
  {
    title: "Sean McDoughnut",
    slug: "sean-mcdoughnut",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/SeanMcDoughnut.png",
  },
  {
    title: "Bangkok",
    slug: "bangkok",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Bangkok.png",
  },
  {
    title: "Intimate",
    slug: "intimate",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Intimate.png",
  },
  {
    title: "Splash",
    slug: "splash",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/SPLASH.png",
  },
  {
    title: "Berlin Art Week",
    slug: "berlin-art-week",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/BerlinArtWeek.png",
  },
  {
    title: "Jesters",
    slug: "jesters",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Jesters.png",
  },
  {
    title: "Ston",
    slug: "ston",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Ston.png",
  },
  {
    title: "Contrast Study NY",
    slug: "contrast-study-ny",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/ContrastStudyNY.png",
  },
  {
    title: "Journal Man",
    slug: "journal-man",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Journal-man.png",
  },
  {
    title: "The Alchemist",
    slug: "the-alchemist",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/TheAlchemist.png",
  },
  {
    title: "Dancing Priests",
    slug: "dancing-priests",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Dancing-Priests.png",
  },
  {
    title: "KO",
    slug: "ko",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/KO.png",
  },
  {
    title: "Triangular Study",
    slug: "triangular-study",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Triangular-study.png",
  },
  {
    title: "HafLet 1",
    slug: "haflet-1",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/HafLet1.png",
  },
  {
    title: "Left Reading",
    slug: "left-reading",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Left-reading.png",
  },
  {
    title: "Welder",
    slug: "welder",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/welder.png",
  },
  {
    title: "HafLet 2",
    slug: "haflet-2",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/HafLet2.png",
  },
  {
    title: "Light Study 1",
    slug: "light-study-1",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Lightstudy1.png",
  },
  {
    title: "What Are You Proud Of?",
    slug: "what-are-you-proud-of",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/What_are_you_proud_of.png",
  },
  {
    title: "Her",
    slug: "her",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Her.png",
  },
  {
    title: "Light Study 2",
    slug: "light-study-2",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Lightstudy2.png",
  },
  {
    title: "Working Men",
    slug: "working-men",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Working-men.png",
  },
  {
    title: "Her 2",
    slug: "her-2",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/Her2.png",
  },
  {
    title: "Me",
    slug: "me",
    medium: "Mixed media",
    year: 2026,
    description: "",
    imagePath: "uploads/ME.png",
  },
];

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    await Artwork.deleteMany();
    await Artwork.insertMany(artworks);
    console.log("Seeded 29 artworks");
    mongoose.connection.close();
  })
  .catch((err) => {
    console.error(err);
    mongoose.connection.close();
  });
